services:

  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - OVH_ENDPOINT=$OVH_ENDPOINT
      - OVH_APPLICATION_KEY=$OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET=$OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY=$OVH_CONSUMER_KEY
      - TRAEFIK_CERTIFICATESRESOLVERS_OVH_ACME_EMAIL=$MAIL
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=ovh
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`proxy.${TYPE_HOST}.ethiryn.fr`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=authentik@file
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
