services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/config:/etc/letsencrypt
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/log:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/domains:/domains
    entrypoint: /bin/sh -c "chmod +x /domains/script.sh && /domains/script.sh"
    networks:
      - frontend
    environment:
      - MAIL=$MAIL

networks:
  frontend:
    external: true
